server:
  port: 8789
  servlet:
    context-path: /canban-auth
spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: 'smtp.gmail.com'
    port: 587

    username: 'canban.service'
    password: 'dguvdojrebduzimp'

    properties:
      mail:
        smtp:
          auth: 'true'
          starttls:
            enable: 'true'
jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g
  lifetime: 36000000
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8181/eureka}
      fetchRegistry: false
