server:
  port: 8193
  servlet:
    context-path: /canban-chat
spring:
  data:
    mongodb:
      database: chat_service
      port: 27018

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8181/eureka}
      fetchRegistry: false